version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: russo-corp-cloudflared
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    env_file:
      - .env

  backend:
    container_name: russo-corp-backend
    build:
      context: ./backend
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - cloudflared
      - db

  frontend:
    container_name: russo-corp-frontend
    build:
      context: ./frontend
    env_file:
        - .env
    volumes:
        - ./frontend:/app
    depends_on:
      - backend

  db:
    image: mariadb:10.6.14
    restart: on-failure
    container_name: russo-corp-db
    volumes:
      - './database:/var/lib/mysql'
      - './backend/database:/docker-entrypoint-initdb.d'
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: 'mysqld --sql_mode=""'
    depends_on:
      - cloudflared

#  adminer:
#    image: adminer
#    container_name: russo-corp-adminer
#    restart: always
#    ports:
#      - 8080:8080

networks:
  default:
    name: russo-corm-network